---
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
  name: color-mesh
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorgateway
  namespace: appmesh-system
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: color-mesh-dns
      serviceName: colorgateway
  backends:
    - virtualService:
        virtualServiceName: colorteller.appmesh-system
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-1
  namespace: appmesh-system
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: color-mesh-dns
      serviceName: colorteller-1
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-blue
  namespace: appmesh-system
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: color-mesh-dns
      serviceName: colorteller-blue
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-2
  namespace: appmesh-system
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: color-mesh-dns
      serviceName: colorteller-2
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: colorteller.appmesh-system
  namespace: appmesh-system
spec:
  meshName: color-mesh
  routes:
    - name: color-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: colorteller-2
              weight: 0
            - virtualNodeName: colorteller-1
              weight: 100
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: colorgateway.appmesh-system
  namespace: appmesh-system
spec:
  meshName: color-mesh
  routes:
    - name: color-route
      http:
        match:
          prefix: /color
        action:
          weightedTargets:
            - virtualNodeName: colorgateway
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: colorgateway
  namespace: appmesh-system
  labels:
    app: colorgateway
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: colorgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorgateway
  namespace: appmesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorgateway
      version: v1
  template:
    metadata:
      labels:
        app: colorgateway
        version: v1
    spec:
      containers:
        - name: colorgateway
          image: "970805265562.dkr.ecr.us-west-2.amazonaws.com/gateway:latest"
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR_TELLER_ENDPOINT"
              value: "colorteller.appmesh-system:9080"
---

# white
---
# black
apiVersion: v1
kind: Service
metadata:
  name: colorteller-1
  namespace: appmesh-system
  labels:
    app: colorteller
    version: black
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: colorteller
    version: black
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-1
  namespace: appmesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
      version: black
  template:
    metadata:
      labels:
        app: colorteller
        version: black
    spec:
      containers:
        - name: colorteller
          image: 970805265562.dkr.ecr.us-west-2.amazonaws.com/colorteller:latest
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR"
              value: "black"
---
# blue
apiVersion: v1
kind: Service
metadata:
  name: colorteller-blue
  namespace: appmesh-system
  labels:
    app: colorteller
    version: blue
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: colorteller
    version: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-blue
  namespace: appmesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
      version: blue
  template:
    metadata:
      labels:
        app: colorteller
        version: blue
    spec:
      containers:
        - name: colorteller
          image: 970805265562.dkr.ecr.us-west-2.amazonaws.com/colorteller:latest
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR"
              value: "blue"
---
# red
apiVersion: v1
kind: Service
metadata:
  name: colorteller-2
  namespace: appmesh-system
  labels:
    app: colorteller
    version: red
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: colorteller
    version: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-2
  namespace: appmesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
      version: red
  template:
    metadata:
      labels:
        app: colorteller
        version: red
    spec:
      containers:
        - name: colorteller
          image: 970805265562.dkr.ecr.us-west-2.amazonaws.com/colorteller:latest
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR"
              value: "red"
---
