apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: colorteller.appmesh-system
  namespace: appmesh-system
spec:
  meshName: color-mesh
  routes:
    - name: color-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: colorteller-1
              weight: 100
            - virtualNodeName: colorteller-2
              weight: 0
